sudo: required
services:
    - docker
    
before_install:
    - docker build -t carlosalonsogtz/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true carlosalonsogtz/docker-react npm run test

language: generic